### PR TITLE
Added emscripten makefile

### PR DESCRIPTION
**Pull request by korczis**

### CODE REVIEW

**Comment by lucasb-eyer** [comment]
This is really neat, thank you!

I'd appreciate if you could move the `index.html` to `examples/javascript.html` or similar, and add a small section into the README.md (maybe a section after ["In Python"](https://github.com/lucasb-eyer/heatmap#in-python)) also linking to index, possibly using http://rawgit.com/.

**Comment by korczis** [comment]
@lucasb-eyer Will try ... ;-)

**Comment by lucasb-eyer** [comment]
Thanks! In case you can't find time for that, I'd rather you let me know than let this PR die.

**Comment by korczis** [comment]
Ok, just close it.

On Sun, Apr 26, 2015 at 1:09 PM, Lucas Beyer <notifications@github.com>
wrote:

> Thanks! In case you can't find time for that, I'd rather you let me know
> than let this PR die.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lucasb-eyer/heatmap/pull/4#issuecomment-96365613>.
>



-- 
<warning>
This e-mail is intended for the named recipient(s). It may contain
privileged and/or confidential information. If you are not one of the
intended recipients, please notify the sender immediately and destroy this
e-mail and attachment(s): you must not copy, distribute, retain or take any
action in reliance upon the email or attachment(s). While all reasonable
efforts are made to safeguard inbound and outbound e-mails, Tomas Korcak
cannot guarantee that attachments are virus-free or are compatible with
your systems, and does not accept liability in respect of viruses or
computer problems experienced. Thank you.
</warning>

<notice>
Your Skills In Reading Have Improved +1
</notice>

<idea>
Some days you're the dog; some days you're the hydrant.
</idea>

**Comment by lucasb-eyer** [comment]
After having stalled this for so long, I'm looking into running it, then documenting it myself and finally merging. A few questions:

1. Why do you save and restore the stack in `index.html`.
2. Why malloc four bytes into `offset` and never use them?
3. `'object'` is [not a known type](https://kripken.github.io/emscripten-site/docs/api_reference/preamble.js.html#cwrap) to cwrap. `'number'` should be used for C-pointers and, even worse, two numbers for 64-bit pointers. Since I never used emscripten before, I assume I'm missing something and just opening the file in firefox/chromium is not how it's supposed to be used?

**Pull request closed without merging**
